using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Gori.CompressedStatics.Generators;

/// <summary>
/// Provides functionality to emit source code for compressed members based on the specified compression algorithm and caching strategy.
/// </summary>
internal static class MemberEmitter
{
    /// <summary>
    /// Builds the generated source for a single individually compressed member, in its own file so
    /// the member re-compresses and re-emits only when its own input changes.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="member">The compression member input.</param>
    /// <param name="supports">The supported compression algorithms and their availability.</param>
    /// <returns>The generated source code as a string.</returns>
    public static string Emit(SourceProductionContext context, CompressionMemberInput member, Supports supports)
    {
        if (supports.DisableBrotli && member.RequestedAlgorithm is CompressionAlgorithm.Brotli)
        {
            string missing = supports.BrotliCompileTime ? "Missing runtime assembly."
                           : supports.BrotliRuntime is not BrotliSupport.None ? "Missing compile time assembly."
                           : "Missing compile time and runtime assemblies.";

            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.BrotliNotAvailable,
                member.Location.ToLocation(),
                missing));

            return string.Empty;
        }

        byte[] uncompressedData = member.GetUncompressedData(out DiagnosticInfo? diagnostic);
        if (diagnostic is not null)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        CompressionAlgorithm algorithm = member.RequestedAlgorithm;
        byte[] compressedData = Compressor.Compress(uncompressedData, ref algorithm, supports.DisableBrotli);
        var storageKind = algorithm.ToStorageKind();

        var builder = CodeStringBuilder.CodeStringBuilder.CreateCSharpBuilder();
        _ = builder.WriteLine($"// <auto-generated />")
                   .WriteLine($"// Compression algorithm: {storageKind}")
                   .WriteLine($"// Uncompressed: {uncompressedData.Length} bytes")
                   .WriteLineIf(
                        storageKind is not StorageKind.Raw,
                        () => $"// Compressed: {compressedData.Length} bytes - {(uncompressedData.Length == 0 ? 0.0 : (double)compressedData.Length / uncompressedData.Length):P2}")
                   .ForceBlankLine();

        string returnType = member.ReturnType.AsKeyword();

        Helper.AppendOpen(builder, member.ContainingType);
        switch (storageKind)
        {
            case StorageKind.Raw:
                string uncompressed = member.ReturnType is ReturnType.String
                        ? SymbolDisplay.FormatLiteral(member.SourceValue ?? string.Empty, true)
                        : uncompressedData.BuildByteArrayLiteral();

                string memberName = member.MemberKind switch
                {
                    MemberKind.Property => member.MemberName,
                    MemberKind.Method => member.MemberName + "()",
                    _ => throw new ArgumentOutOfRangeException(nameof(member), member.MemberKind, null),
                };

                _ = builder.WriteLine($"""
                        {member.Accessibility} static partial {returnType} {memberName}
                            => {uncompressed};{CodeStringBuilder.CodeStringBuilder.IndentDecreasePost}
                        """).ForceBlankLine();
                break;

            case StorageKind.Brotli:
            case StorageKind.GZip:
            case StorageKind.Deflate:
            default:
                string uniqueToken = Helper.Sanitize(member.MemberName);
                string compressedFieldName = Const.CompressedFieldNamePrefix + uniqueToken;
                string cacheFieldName = Const.CacheFieldNamePrefix + uniqueToken;
                string decompressCall = Helper.BuildDecompressCall(member.ReturnType, storageKind, compressedFieldName);

                _ = builder.WriteLine($"private static readonly byte[] {compressedFieldName} = {compressedData.BuildByteArrayLiteral()};")
                           .ForceBlankLine();

                _ = member.MemberKind switch
                {
                    MemberKind.Property => member.CacheMode switch
                    {
                        CompressionCacheMode.LazyThreadSafe
                            => builder.WriteLine($"""
                                        private static readonly global::System.Lazy<{returnType}> {cacheFieldName} = new(() => {decompressCall});

                                        {member.Accessibility} static partial {returnType} {member.MemberName} => {cacheFieldName}.Value;
                                        """).ForceBlankLine(),

                        CompressionCacheMode.Lazy
                            => builder.WriteLine($"""
                                        private static {returnType} {cacheFieldName};

                                        {member.Accessibility} static partial {returnType} {member.MemberName}
                                            => {cacheFieldName} ??= {decompressCall};{CodeStringBuilder.CodeStringBuilder.IndentDecreasePost}
                                        """).ForceBlankLine(),

                        CompressionCacheMode.OnInit or _
                            => builder.WriteLine($"""
                                        private static readonly {returnType} {cacheFieldName} = {decompressCall};

                                        {member.Accessibility} static partial {returnType} {member.MemberName} => {cacheFieldName};
                                        """).ForceBlankLine(),
                    },

                    MemberKind.Method => builder.WriteLine($"""
                            {member.Accessibility} static partial {returnType} {member.MemberName}()
                                => {decompressCall};{CodeStringBuilder.CodeStringBuilder.IndentDecreasePost}
                            """).ForceBlankLine(),

                    _ => throw new ArgumentOutOfRangeException(nameof(member), member.MemberKind, null),
                };
                break;
        }

        Helper.AppendClose(builder, member.ContainingType);

        return builder.ToString();
    }
}
