using System.Globalization;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Gori.CompressedStatics.Generators;

/// <summary>
/// Emits the complete generated source for a single containing type: its individually compressed
/// members plus, when present, the assembled tar blob, its initializer, and a static constructor.
/// </summary>
internal static class TypeEmitter
{
    /// <summary>
    /// Builds the generated source for a type's assembled tar blob, or an empty string when there
    /// is nothing to emit.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="tar">The tar members to emit.</param>
    /// <param name="supports">The compression algorithm support information.</param>
    /// <returns>The generated source code for the tar members.</returns>
    public static string EmitTar(SourceProductionContext context, TarMembers tar, Supports supports)
    {
        if (tar.Members.Length == 0)
        {
            return string.Empty;
        }

        if (supports.DisableBrotli && tar.Algorithm is CompressionAlgorithm.Brotli)
        {
            string missing = supports.BrotliCompileTime ? "Missing runtime assembly."
                           : supports.BrotliRuntime is not BrotliSupport.None ? "Missing compile time assembly."
                           : "Missing compile time and runtime assemblies.";

            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.BrotliNotAvailable,
                tar.Location.ToLocation(),
                missing));

            return string.Empty;
        }

        var tarMembers = new List<(CompressionMemberInput Member, int Index, int Length)>();

        using MemoryStream tarStream = new();

        foreach (CompressionMemberInput member in tar.Members)
        {
            byte[] data = member.GetUncompressedData(out DiagnosticInfo? diagnostic);
            if (diagnostic is not null)
            {
                context.ReportDiagnostic(diagnostic.ToDiagnostic());
            }

            if (data.Length == 0)
            {
                tarMembers.Add((member, 0, 0));
            }
            else
            {
                int index = (int)tarStream.Position;
                tarStream.Write(data, 0, data.Length);
                tarMembers.Add((member, index, data.Length));
            }
        }

        CompressionAlgorithm algorithm = tar.Algorithm;
        byte[] tarData = tarStream.ToArray();
        byte[] compressedData = Compressor.Compress(tarData, ref algorithm, supports.DisableBrotli);
        var storageKind = algorithm.ToStorageKind();

        var builder = CodeStringBuilder.CodeStringBuilder.CreateCSharpBuilder();
        _ = builder.WriteLine($"// <auto-generated />")
                   .WriteLine($"// Compression algorithm: {storageKind}")
                   .WriteLine($"// Uncompressed: {tarData.Length} bytes")
                   .WriteLineIf(storageKind is not StorageKind.Raw, () => $"// Compressed: {compressedData.Length} bytes - {(tarData.Length == 0 ? 0.0 : (double)compressedData.Length / tarData.Length):P2}")
                   .ForceBlankLine();

        Helper.AppendOpen(builder, tar.Type);

        if (tar.Type.HasStaticConstructor)
        {
            AppendTarLazy(builder, tar, compressedData, storageKind, tarMembers);
        }
        else
        {
            AppendTarStaticConstructor(builder, tar, compressedData, storageKind, tarMembers);
        }

        Helper.AppendClose(builder, tar.Type);

        return builder.ToString();
    }

    /// <summary>
    /// Emits tar members for a type that has no user-declared static constructor. Values are assigned
    /// directly inside a generated static constructor, which legally initializes read-only auto
    /// properties (non-partial) and partial-property backing fields alike.
    /// </summary>
    private static void AppendTarStaticConstructor(
        CodeStringBuilder.CodeStringBuilder builder,
        TarMembers tar,
        byte[] compressedData,
        StorageKind storage,
        List<(CompressionMemberInput Member, int Index, int Length)> members)
    {
        StringBuilder ctorBody = new();
        bool allRaw = storage is StorageKind.Raw || compressedData.Length == 0;

        if (!allRaw)
        {
            _ = builder.WriteLine($"private static readonly byte[] {Const.TarCompressedFieldName} = {compressedData.BuildByteArrayLiteral()};")
                       .ForceBlankLine();

            string decompressCall = Helper.BuildDecompressCall(ReturnType.ByteArray, storage, Const.TarCompressedFieldName);
            _ = ctorBody.AppendLine($"byte[] {Const.DecompressedTarFieldName} = {decompressCall};")
                        .AppendLine();
        }

        foreach ((CompressionMemberInput member, int index, int length) in members)
        {
            string fieldName = Const.CacheFieldNamePrefix + Helper.Sanitize(member.MemberName);
            string returnType = member.ReturnType.AsKeyword();

            if (member.IsPartial)
            {
                _ = builder.WriteLine($"""
                        private static {returnType} {fieldName};
                        {member.Accessibility} static partial {returnType} {member.MemberName} => {fieldName};
                        """).ForceBlankLine();
            }
            else
            {
                fieldName = member.MemberName;
            }

            string valueExpression = allRaw || length == 0
                ? BuildDirectLiteral(member)
                : BuildSegmentExpression(member, index, length, Const.DecompressedTarFieldName);

            _ = ctorBody.AppendLine($"{fieldName} = {valueExpression};");
        }

        string typeName = tar.Type.Declarations.IsDefaultOrEmpty ? string.Empty : StripTypeParameters(tar.Type.Declarations[^1].Name);
        _ = builder.WriteLine($"static {typeName}()")
                   .WriteLine("{")
                   .WriteLine(ctorBody.ToString())
                   .WriteLine("}");
    }

    /// <summary>
    /// Emits tar members for a type that already declares a static constructor. Every tar member must
    /// be partial; values load through partial-property backing-field initializers that pull slices
    /// from a shared, lazily decompressed buffer. The buffer is released once all slices are read.
    /// </summary>
    private static void AppendTarLazy(
        CodeStringBuilder.CodeStringBuilder builder,
        TarMembers tar,
        byte[] compressedData,
        StorageKind storage,
        List<(CompressionMemberInput Member, int Index, int Length)> members)
    {
        bool allRaw = storage is StorageKind.Raw || compressedData.Length == 0;
        if (!allRaw)
        {
            _ = builder.WriteLine($"private static readonly byte[] {Const.TarCompressedFieldName} = {compressedData.BuildByteArrayLiteral()};")
                       .ForceBlankLine();

            string decompressCall = Helper.BuildDecompressCall(ReturnType.ByteArray, storage, Const.TarCompressedFieldName);
            int total = members.Count(m => m.Length > 0);

            _ = builder.WriteLine($$"""
                        private static byte[]? {{Const.TarBufferFieldName}};
                        private static int {{Const.TarBufferUseCountFieldName}};

                        private static byte[] {{Const.TarBufferMethodName}}()
                        {
                            byte[] {{Const.DecompressedTarFieldName}} = global::System.Threading.LazyInitializer.EnsureInitialized(ref {{Const.TarBufferFieldName}}, static () => {{decompressCall}});
                            if (global::System.Threading.Interlocked.Increment(ref {{Const.TarBufferUseCountFieldName}}) == {{total}})
                            {
                                {{Const.TarBufferFieldName}} = null;
                            }

                            return {{Const.DecompressedTarFieldName}};
                        }
                        """).ForceBlankLine();
        }

        foreach ((CompressionMemberInput member, int index, int length) in members)
        {
            string returnType = member.ReturnType.AsKeyword();
            string fieldName = Const.CacheFieldNamePrefix + Helper.Sanitize(member.MemberName);
            string valueExpression = allRaw || length == 0
                ? BuildDirectLiteral(member)
                : BuildSegmentExpression(member, index, length, $"{Const.TarBufferMethodName}()");

            _ = builder.WriteLine($"""
                    private static {returnType} {fieldName} = {valueExpression};
                    {member.Accessibility} static partial {returnType} {member.MemberName} => {fieldName};
                    """).ForceBlankLine();
        }
    }

    private static string BuildSegmentExpression(CompressionMemberInput member, int offset, int length, string bufferExpression)
    {
        string method = member.ReturnType is ReturnType.String ? "SegmentAsString" : "SegmentAsBytes";
        return $"{Const.DecompressStaticsClassFullName}.{method}({bufferExpression}, {offset.ToString(CultureInfo.InvariantCulture)}, {length.ToString(CultureInfo.InvariantCulture)})";
    }

    private static string BuildDirectLiteral(CompressionMemberInput direct)
        => direct.ReturnType is ReturnType.String
            ? SymbolDisplay.FormatLiteral(direct.SourceValue ?? string.Empty, true)
            : direct.GetUncompressedData(out _).BuildByteArrayLiteral();

    private static string StripTypeParameters(string name)
    {
        int index = name.IndexOf('<');
        return index < 0 ? name : name[..index];
    }
}
