<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Gori.CompressedStatics</PackageId>
    <PackageVersion>1.0.0.0</PackageVersion>
    <Authors>Tim Koopman</Authors>
    <PackageLicenseExpression>MIT-0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/tkoopman/Gori.CompressedStatics</RepositoryUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Description>Gori.CompressedStatics can compress selected static property or method values at compile time and decompress them at runtime.</Description>
    <PackageTags>Gori.CompressedStatics, analyzers</PackageTags>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IsRoslynComponent>true</IsRoslynComponent>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddAnalyzersToOutput</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <PropertyGroup>
    <PackageOutputPath>..\..\LocalPackages</PackageOutputPath>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-all</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\Usage.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\AnalyzerReleases.Shipped.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\AnalyzerReleases.Unshipped.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gori.CompressedStatics.CodeFix\Gori.CompressedStatics.CodeFix.csproj" />
    <ProjectReference Include="..\Gori.CompressedStatics\Gori.CompressedStatics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- CodeStringBuilder and it's dependency BCL Memory-->
    <PackageReference Include="Gori.CodeStringBuilder" Version="1.1.2" PrivateAssets="all" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Bcl.Memory" Version="10.0.11" PrivateAssets="all" GeneratePathProperty="true" />
  </ItemGroup>

  <Target Name="_AddAnalyzersToOutput">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)\Gori.CompressedStatics.dll" PackagePath="analyzers/dotnet/cs" Visible="false" />
      <TfmSpecificPackageFile Include="$(OutputPath)\Gori.CompressedStatics.CodeFix.dll" PackagePath="analyzers/dotnet/cs" Visible="false" />
      <TfmSpecificPackageFile Include="$(PkgGori_CodeStringBuilder)\lib\netstandard2.0\Gori.CodeStringBuilder.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
      <TfmSpecificPackageFile Include="$(PkgMicrosoft_Bcl_Memory)\lib\netstandard2.0\Microsoft.Bcl.Memory.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>
  </Target>

</Project>
