// <auto-generated />

namespace Gori.DecompressStatics
{
    internal enum Algorithm
    {
        Brotli,
        GZip,
        Deflate,
    }

    internal static class DecompressStatic
    {
        public static byte[] AsBytes(byte[] compressedValue, global::Gori.DecompressStatics.Algorithm algorithm)
        {
            using var memoryStream = new global::System.IO.MemoryStream(compressedValue);
            using global::System.IO.Stream compressionStream = algorithm switch
            {
                global::Gori.DecompressStatics.Algorithm.Brotli => ${BrotliStream},
                global::Gori.DecompressStatics.Algorithm.GZip => new global::System.IO.Compression.GZipStream(memoryStream, global::System.IO.Compression.CompressionMode.Decompress),
                global::Gori.DecompressStatics.Algorithm.Deflate => new global::System.IO.Compression.DeflateStream(memoryStream, global::System.IO.Compression.CompressionMode.Decompress),
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(algorithm), algorithm, null),
            };
            using var resultStream = new global::System.IO.MemoryStream();
            compressionStream.CopyTo(resultStream);
            return resultStream.ToArray();
        }

        public static string AsString(byte[] compressedValue, global::Gori.DecompressStatics.Algorithm algorithm)
        {
            using var memoryStream = new global::System.IO.MemoryStream(compressedValue);
            using global::System.IO.Stream compressionStream = algorithm switch
            {
                global::Gori.DecompressStatics.Algorithm.Brotli => ${BrotliStream},
                global::Gori.DecompressStatics.Algorithm.GZip => new global::System.IO.Compression.GZipStream(memoryStream, global::System.IO.Compression.CompressionMode.Decompress),
                global::Gori.DecompressStatics.Algorithm.Deflate => new global::System.IO.Compression.DeflateStream(memoryStream, global::System.IO.Compression.CompressionMode.Decompress),
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(algorithm), algorithm, null),
            }
;
            using var resultStream = new global::System.IO.MemoryStream();
            compressionStream.CopyTo(resultStream);

#if NET8_0_OR_GREATER
            if (resultStream.TryGetBuffer(out global::System.ArraySegment<byte> buffer))
            {
                return global::System.Text.Encoding.Unicode.GetString(buffer.Array, buffer.Offset, (int)resultStream.Length);
            }
#endif

            return global::System.Text.Encoding.Unicode.GetString(resultStream.ToArray());
        }

        public static byte[] SegmentAsBytes(byte[] decompressed, int offset, int length)
        {
            var result = new byte[length];
            global::System.Array.Copy(decompressed, offset, result, 0, length);
            return result;
        }

        public static string SegmentAsString(byte[] decompressed, int offset, int length)
            => global::System.Text.Encoding.Unicode.GetString(decompressed, offset, length);
    }
}
