<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.9.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="5.9.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gori.CompressedStatics.CodeFix\Gori.CompressedStatics.CodeFix.csproj" />
    <ProjectReference Include="..\Gori.CompressedStatics\Gori.CompressedStatics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestAssets\AdditionalFiles\content\" />
  </ItemGroup>

</Project>
